# Site settings
# These are used to personalize your new site.
title: Michael R. Ludwikowski III # your name here
logo: "/images/MichaelLudwikowskiPicture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2026)
  <br /><br />
  <a href="https://michaelludwikowski.github.io/">View My Resume</a>
  <br /><br />
  <a href="https://csuniv.joinhandshake.com/profiles/pns3v9">View My Handshake Profile</a>
repository: "MichaelLudwikowski/MichaelLudwikowski.giyhub.io"
github_username:  MichaelLudwikowski # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

